title: Mikonaut
description: Space pics when I can stay up late, flower pics when the sun is shining.
sass:
  style: compressed
plugins:
- jekyll-remote-theme
- jekyll-paginate
- jekyll-favicon
url: "https://hassimir.github.io" 
baseurl: ""
paginate: 20
paginate_path: "/page:num/"
